Rango_fixed/tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w-]+)/$',
        views.show_category, name='show_category'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Rango_fixed/tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rango_fixed/tango_with_django_project/rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes =  models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    # required line - links UserProfile to user model instance
    user = models.OneToOneField(User)

    #additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.username

    def __unicode__(self):
        return self.username

Rango_fixed/tango_with_django_project/rango/forms.py
from django import forms
from rango.models import Page, Category
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

Rango_fixed/tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    most_viewed = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'viewed': most_viewed}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    return response

def about(request):
    context_dict = {}
    context_dict['visits'] = request.session['visits']
    visitor_cookie_handler(request)
    response = render(request, 'rango/about.html', context=context_dict)
    return response
# Create your views here.
def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages

        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})

def user_login(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else: 
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango/login.html', {})

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

# helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# helper method function for cookie handler
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))

    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        #set the last visist cookie
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits
    

Rango_fixed/tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    About
{% endblock %}

{% block body_block %}
     <body>
        <h1>Rango says...</h1>
        <div>
            here is the about page! <br />
        </div>
        <div> 
            This tutorial has been put together by steve quinn
        </div>
            <div>
                <p> visits: {{ visits }}</p>
            <img src="{% static "images/rango2.jpg" %}"
                alt="other picture of Rango" /> <!-- New line -->
            <img src="/media/cat.jpg"
                alt="Rango: a green lizard" />
            </div>
    </body>
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
      <body>
        <h1>Add a Category</h1>
        <div>
            <form id="category_form" method="post" action="/rango/add_category/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
                {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
            </form>
        </div>
    </body>
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    About
{% endblock %}

{% block body_block %}
      <body>
        <h1>Add a Page</h1>
        <div>
            {% if category %}
            <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
                {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
            </form>

            {% else %}
                <strong> A Category by this name does not exist</strong>
            {% endif %}
        </div>
    </body>
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
           {% block body_block %}
           {% endblock %}
        </div> 
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'rango:login' %}">Sign In</a></li>
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
      
    </body>
</html>

Rango_fixed/tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>


        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category.</strong> <br />
            {% endif %}
                <ul>
                {% if user.is_authenticated %}
                <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
            
                {% endif %}
                
            </ul>
                
        {% else %}
            The specified category does not exist!
        {% endif %}
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/cats.html
{% for c in cats %}
    {% if c == act_cat %}
        <li> 
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
        </li>
    
    {% else %}
    <li> 
        
        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
    </li>
    {% endif %}
{% endfor %}

Rango_fixed/tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <body>
        <h1>Rango says...
       
            {% if user.is_authenticated %}
                howdy {{ user.username }}!
            {% else %}
                hey there partner!
            {% endif %}
            </h1>

        <div>
            <h1> Most Liked Categories</h1>
        {% if categories %}
        <ul>
            {% for category in categories %}
                <li><a href="{% url 'rango:show_category' category.slug %}"
                >{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </div>
        <div>
            <h1>Most Viewed Pages</h1>
        </div>
        <div>
        {% if viewed %}
        <ul>
        {% for page in viewed %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li> 
            {% endfor %}
            </ul> 
            {% else %}
            <strong>No pages currently in category.</strong> 
            {% endif %}
    </div>
        <p> visits: {{ visits }}</p>

        <div>
            <img src="{% static "images/rango.jpg" %}"
                alt="Picture of Rango" /> <!-- New line -->
            </div>
    </body>
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}


{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}


{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
            <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
            <form id="user_form" method="post" action="{% url 'rango:register' %}"
                  enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Display each form -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

Rango_fixed/tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    About
{% endblock %}

{% block body_block %}
     <body>
        <h1>Rango says...</h1>
        <div>
            Welcome to the restricted page! <br />
        </div>
        <div> 
            <strong>Do you feel special??!</strong>
        </div>
            <div>
            
            </div>
    </body>
{% endblock %}